freebsd_instance:
  image_family: freebsd-12-1

freebsd_task:
  env:
    matrix:
      - OCAML_VERSION: 4.13.1
      - OCAML_VERSION: 4.14.0
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=$OCAML_VERSION
  mirage_script: eval `opam env` && opam install -y "mirage>=4" lwt
  configure_script: eval `opam env` && mirage configure -t hvt
  depend_script: eval `opam env` && gmake depend
  build_script: eval `opam env` && mirage build
  unipi_artifacts:
    path: dist/unipi.hvt
