freebsd_instance:
  image_family: freebsd-13-2

freebsd_task:
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=4.13.1
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && mirage configure -t hvt
  depend_script: eval `opam env` && gmake depend
  build_script: eval `opam env` && gmake build
  unipi_artifacts:
    path: dist/unipi.hvt

freebsd_monitoring_task:
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=4.14.1
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && mirage configure -t hvt --enable-monitoring
  depend_script: eval `opam env` && gmake depend
  build_script: eval `opam env` && gmake build
  unipi_artifacts:
    path: dist/unipi.hvt
