(* This should ideally be generated by the Mirage tool, but it and functoria
   are a pain to work with *)
module K = struct
  let v4_optional_network =
    Mirage_runtime.register_arg @@
    Mirage_runtime_network.V4.optional_network ()

  let v4_gateway_none =
    Mirage_runtime.register_arg @@
    Mirage_runtime_network.V4.gateway None

  let v6_network_none =
    Mirage_runtime.register_arg @@
    Mirage_runtime_network.V6.network None

  let v6_gateway_none =
    Mirage_runtime.register_arg @@
    Mirage_runtime_network.V6.gateway None

  let v6_accept_router_advertisements =
    Mirage_runtime.register_arg @@
    Mirage_runtime_network.V6.accept_router_advertisements ()

  let ipv4_only = Mirage_runtime.register_arg @@
    Mirage_runtime_network.ipv4_only ()

  let ipv6_only = Mirage_runtime.register_arg @@
    Mirage_runtime_network.ipv6_only ()

  let mirage_runtime_network_dns_servers_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.dns_servers None

  let mirage_runtime_network_dns_timeout_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.dns_timeout None

  let mirage_runtime_network_dns_cache_size_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.dns_cache_size None

  let mirage_runtime_network_he_aaaa_timeout_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.he_aaaa_timeout None

  let mirage_runtime_network_he_connect_delay_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.he_connect_delay None

  let mirage_runtime_network_he_connect_timeout_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.he_connect_timeout None

  let mirage_runtime_network_he_resolve_timeout_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.he_resolve_timeout None

  let mirage_runtime_network_he_resolve_retries_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.he_resolve_retries None

  let mirage_runtime_network_he_timer_interval_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.he_timer_interval None

  let mirage_runtime_network_ssh_key_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.ssh_key None

  let mirage_runtime_network_ssh_password_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.ssh_password None

  let mirage_runtime_network_ssh_authenticator_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.ssh_authenticator None

  let mirage_runtime_network_tls_authenticator_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.tls_authenticator None

  let mirage_runtime_network_http_headers_none__key = Mirage_runtime.register_arg @@
    Mirage_runtime_network.http_headers None
end

module Main (Netif : Mirage_net.S) = struct
  module Ethernet = Ethernet.Make(Netif)
  module Arp = Arp.Make(Ethernet)
  module Dhcp = Dhcp_ipv4.Make(Netif)(Ethernet)(Arp)
  module Netif = Dhcp_ipv4.Proj_net(Dhcp)
  module Ipv4 = Dhcp_ipv4.Proj_ipv4(Dhcp)
  module Lease = Dhcp_ipv4.Proj_lease(Dhcp)
  module Ipv6 = Ipv6.Make(Netif)(Ethernet)
  module Icmpv4 = Icmpv4.Make(Ipv4)
  module Ipv4v6 = Tcpip_stack_direct.IPV4V6(Ipv4)(Ipv6)
  module Udp = Udp.Make(Ipv4v6)
  module Tcp = Utcp_mirage.Make(Ipv4v6)
  module Stack = Tcpip_stack_direct.MakeV4V6(Netif)(Ethernet)(Arp)(Ipv4v6)(Icmpv4)(Udp)(Tcp)
  module Tcpip = Tcpip_stack_direct.TCPV4V6(Stack)
  module Happy_eyeballs_mirage = Happy_eyeballs_mirage.Make(Stack)
  module Dns_client = Dns_client_mirage.Make(Stack)(Happy_eyeballs_mirage)
  module Mimic_happy_eyeballs = Mimic_happy_eyeballs.Make(Stack)(Happy_eyeballs_mirage)(Dns_client)
  module Git_net_tcp = Git_net.TCP.Make(Tcpip)(Mimic_happy_eyeballs)
  module Git_net_ssh = Git_net.SSH.Make(Tcpip)(Mimic_happy_eyeballs)
  module Git_net_http = Git_net.HTTP.Make(Tcpip)(Mimic_happy_eyeballs)

  module Dns_mirage = Dns_mirage.Make(Stack)
  module Start = Unikernel.Main(struct end)(Stack)

  let tlsa_is usage sel typ t =
    let module Tlsa = Dns.Tlsa in
    t.Tlsa.cert_usage = usage &&
    t.Tlsa.selector = sel &&
    t.Tlsa.matching_type = typ

  let is_certificate t =
    let module Tlsa = Dns.Tlsa in
    tlsa_is Tlsa.Domain_issued_certificate Tlsa.Full_certificate Tlsa.No_hash t

  let is_ca_certificate t =
    let module Tlsa = Dns.Tlsa in
    tlsa_is Tlsa.CA_constraint Tlsa.Full_certificate Tlsa.No_hash t


  (* may be better suited in X509? *)
  let cert_matches_csr ?until now csr cert =
    let until = match until with None -> now | Some x -> x in
    let csr_key = X509.Signing_request.((info csr).public_key)
    and csr_hostnames = X509.Signing_request.hostnames csr
    and cert_key = X509.Certificate.public_key cert
    and cert_hostnames = X509.Certificate.hostnames cert
    and (st, en) = X509.Certificate.validity cert
    in
    let valid = Ptime.is_later ~than:st now && Ptime.is_later ~than:until en in
    if not (String.equal (X509.Public_key.fingerprint cert_key) (X509.Public_key.fingerprint csr_key)) then begin
      Logs.info (fun m -> m "public key of CSR and certificate %a do not match"
                   X509.Certificate.pp cert);
      false
    end else if not (X509.Host.Set.equal cert_hostnames csr_hostnames) then begin
      Logs.info (fun m -> m "hostnames of CSR %a and certificate %a do not match"
                   X509.Host.Set.pp csr_hostnames X509.Host.Set.pp cert_hostnames);
      false
    end else if not valid then begin
      let pp_pt = Ptime.pp_rfc3339 () in
      Logs.info (fun m -> m "Certificate is not valid now %a (until %a), it is \
                            valid from %a until %a)"
                   pp_pt now pp_pt until pp_pt st pp_pt en);
      false
    end else
      true

  let tlsas_to_certchain host now csr tlsas =
    let certificates, ca_certificates =
      Dns.Rr_map.Tlsa_set.fold (fun tlsa (certs, cacerts as acc) ->
          if is_certificate tlsa || is_ca_certificate tlsa then
            match X509.Certificate.decode_der tlsa.Dns.Tlsa.data with
            | Error (`Msg msg) ->
              Logs.warn (fun m -> m "couldn't decode tlsa record %a: %s (%a)"
                            Domain_name.pp host msg
                            Ohex.pp tlsa.Dns.Tlsa.data);
              acc
            | Ok cert ->
              match is_certificate tlsa, is_ca_certificate tlsa with
              | true, _ -> (cert :: certs, cacerts)
              | _, true -> (certs, cert :: cacerts)
              | _ -> acc
          else acc)
        tlsas ([], [])
    in
    match List.find_opt (cert_matches_csr now csr) certificates with
    | None -> Error `No_tlsa
    | Some server_cert ->
      match List.rev (X509.Validation.build_paths server_cert ca_certificates) with
      | (_server :: chain) :: _ -> Ok (server_cert, chain)
      | _ -> Ok (server_cert, []) (* build_paths always returns the server_cert *)

  let query rng now host csr =
    let open Dns in
    let header =
      let id = Randomconv.int16 rng in
      (id, Packet.Flags.empty)
    and question = Packet.Question.create host Tlsa
    in
    let request = Packet.create header question `Query in
    let out, _ = Packet.encode `Tcp request
    and react data =
      match Packet.decode data with
      | Error e -> Error (`Decode e)
      | Ok reply ->
        match Packet.reply_matches_request ~request reply with
        | Ok (`Answer (answer, _)) ->
          begin match Name_rr_map.find host Tlsa answer with
            | None -> Error `No_tlsa
            | Some (_, tlsas) -> tlsas_to_certchain host now csr tlsas
          end
        | Ok (`Rcode_error (Rcode.NXDomain, Opcode.Query, _)) -> Error `No_tlsa
        | Ok reply -> Error (`Unexpected_reply reply)
        | Error e -> Error (`Bad_reply (e, reply))
    in
    Ok (out, react)


  let query_certificate flow name csr =
    let open Lwt.Infix in
    match query Mirage_crypto_rng.generate (Mirage_ptime.now ()) name csr with
    | Error e -> Lwt.return (Error e)
    | Ok (out, cb) ->
      Dns_mirage.send_tcp (Dns_mirage.flow flow) (Cstruct.of_string out) >>= function
      | Error () -> Lwt.return (Error (`Msg "couldn't send tcp"))
      | Ok () ->
        Dns_mirage.read_tcp flow >|= function
        | Error () -> Error (`Msg "error while reading answer")
        | Ok data -> match cb (Cstruct.to_string data) with
          | Error e -> Error e
          | Ok cert -> Ok cert

  let query_certificate csr stack (ip, domain) =
    let open Lwt.Syntax in
    let rec wait_for_cert ?(retry = 30) flow =
      if retry = 0 then
        Lwt.return (Error (`Msg "too many retries, giving up"))
      else
          let* r = query_certificate flow domain csr in
          match r with
          | Ok (cert, _) as ok ->
            Logs.debug (fun m -> m "Received cert: %a" X509.Certificate.pp cert);
            Lwt.return ok
          | Error (#Dns_certify.q_err) ->
            let* () = Mirage_sleep.ns (Duration.of_sec 2) in
            wait_for_cert ~retry:(pred retry) flow
          | Error `Msg _ as e ->
            Lwt.return e
    in
    let* r = Stack.TCP.create_connection (Stack.tcp stack) (ip, 53) in
    match r with
    | Error e ->
      Lwt.return_error (`Msg (Fmt.str "error while connecting to nameserver: %a"
                                Stack.TCP.pp_error e))
    | Ok flow ->
      Lwt.finalize
        (fun () -> wait_for_cert (Dns_mirage.of_flow flow))
        (fun () -> Stack.TCP.close flow)

  let get_certificate privkey csr lease dns_client =
    match lease with
    | None -> Lwt.return_error `No_lease
    | Some lease ->
      let vivso = Dhcp_wire.collect_vi_vendor_info lease in
      match
        Option.bind (List.assoc_opt 49836l vivso)
          (List.assoc_opt 1)
      with
      | None -> Lwt.return_error `No_mirage_certify
      | Some data ->
        let open Lwt_result.Syntax in
        let* ip, domain = Lwt.return (Dnsvizor_csr.decode_src data) in
        let+ cert, certs = query_certificate csr dns_client (ip, domain) in
        `Single (cert :: certs, privkey)

  let start netif =
    let open Lwt.Syntax in
    let privkey = X509.Private_key.generate `P256 in
    let hostname =
      match Unikernel.K.hostname () with
      | None -> failwith "--hostname is required"
      | Some hostname -> hostname
    in
    let csr =
      let dn = [ X509.Distinguished_name.(Relative_distinguished_name.singleton (CN hostname)) ] in
      X509.Signing_request.create dn privkey
      |> Result.get_ok
    in
    let* ethernet = Ethernet.connect netif in
    let* arp = Arp.connect ethernet in
    let* dhcp_ipv4 =
      let v4_optional_network = K.v4_optional_network ()
      and v4_gateway_none = K.v4_gateway_none ()
      and ipv6_only = K.ipv6_only () in
      let requests = Some Dhcp_wire.[
          SUBNET_MASK; ROUTERS; DNS_SERVERS; VI_VENDOR_INFO; CLIENT_FQDN ]
      in
      let options = [
        Dhcp_wire.Client_fqdn ([ `Server_A ], Domain_name.of_string_exn hostname);
        Dhcp_wire.Vi_vendor_class [ 49836l, [ Dnsvizor_csr.encode csr ] ];
      ] in
      Dhcp.connect ?requests ~options ~no_init:ipv6_only ?cidr:v4_optional_network
        ?gateway:v4_gateway_none netif ethernet arp
    in
    let* netif = Netif.connect dhcp_ipv4 in
    let* ipv4 = Ipv4.connect dhcp_ipv4 in
    let* lease = Lease.connect dhcp_ipv4 in
    let* ipv6 =
      let no_init = K.ipv4_only ()
      and handle_ra = K.v6_accept_router_advertisements ()
      and cidr = K.v6_network_none ()
      and gateway = K.v6_gateway_none ()
      in
      Ipv6.connect ~no_init ~handle_ra ?cidr ?gateway netif ethernet
    in
    let* ipv4v6 =
      let ipv4_only = K.ipv4_only () and ipv6_only = K.ipv6_only () in
      Ipv4v6.connect ~ipv4_only ~ipv6_only ipv4 ipv6
    in
    let* icmpv4 = Icmpv4.connect ipv4 in
    let* udp = Udp.connect ipv4v6 in
    let tcp = Tcp.connect "service" ipv4v6 in
    let* stack = Stack.connect netif ethernet arp ipv4v6 icmpv4 udp tcp in
    let* happy_eyeballs_mirage =
      let aaaa_timeout = K.mirage_runtime_network_he_aaaa_timeout_none__key ()
      and connect_delay = K.mirage_runtime_network_he_connect_delay_none__key ()
      and connect_timeout = K.mirage_runtime_network_he_connect_timeout_none__key ()
      and resolve_timeout = K.mirage_runtime_network_he_resolve_timeout_none__key ()
      and resolve_retries = K.mirage_runtime_network_he_resolve_retries_none__key ()
      and timer_interval = K.mirage_runtime_network_he_timer_interval_none__key () in
      Happy_eyeballs_mirage.connect_device ?aaaa_timeout ?connect_delay ?connect_timeout
        ?resolve_timeout ?resolve_retries ?timer_interval
        stack
    in
    let* dns_client =
      let nameservers =
        match K.mirage_runtime_network_dns_servers_none__key (), lease with
        | None, None -> None
        | Some ns, _ -> Some ns
        | None, Some lease ->
          let nameservers = Dhcp_wire.collect_dns_servers lease in
          if nameservers = [] then None
          else
            Some (List.concat_map (fun ip -> [ Fmt.str "udp:%a" Ipaddr.V4.pp ip;
                                               Fmt.str "tcp:%a" Ipaddr.V4.pp ip])
                    nameservers)
      in
      let timeout = K.mirage_runtime_network_dns_timeout_none__key ()
      and cache_size = K.mirage_runtime_network_dns_cache_size_none__key () in
      Dns_client.connect ?nameservers ?timeout ?cache_size (stack, happy_eyeballs_mirage)
    in
    let* mimic_happy_eyeballs = Mimic_happy_eyeballs.connect happy_eyeballs_mirage in
    let* git_net_tcp = Git_net_tcp.connect mimic_happy_eyeballs in
    let* git_net_ssh =
      let authenticator = K.mirage_runtime_network_ssh_authenticator_none__key ()
      and key = K.mirage_runtime_network_ssh_key_none__key ()
      and password = K.mirage_runtime_network_ssh_password_none__key () in
      let* t = Git_net_ssh.connect mimic_happy_eyeballs in
      Git_net_ssh.with_optionnal_key ?authenticator ~key ~password t
    in
    let* git_net_http =
      let headers = K.mirage_runtime_network_http_headers_none__key ()
      and authenticator = K.mirage_runtime_network_tls_authenticator_none__key () in
      let* t = Git_net_http.connect mimic_happy_eyeballs in
      Git_net_http.with_optional_tls_config_and_headers ?headers ?authenticator t
    in
    let mimic_merge = Mimic.merge git_net_tcp (Mimic.merge git_net_ssh git_net_http) in
    let* cert = get_certificate privkey csr lease stack in
    match cert with
    | Error `Msg e ->
      Logs.err (fun m -> m "Issue getting certificate: %s" e);
      exit 9
    | Error `No_tlsa ->
      Logs.err (fun m -> m "Issue getting certificate: no TLSA");
      exit 9
    | Error `No_lease ->
      Logs.err (fun m -> m "No lease");
      exit 9
    | Error `No_mirage_certify ->
      Logs.err (fun m -> m "No certificate from DHCP server");
      exit 9
    | Ok cert ->
      Start.start mimic_merge stack cert
end
